/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MAIN_PROJECT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class driver_reg_form extends javax.swing.JFrame {
    Connection con = null;
      PreparedStatement pst = null;
      ResultSet rs = null;
    /**
     * Creates new form driver_reg_form
     */
    public driver_reg_form() {
        initComponents();
        try {
            // Establish the database connection in the constructor
            con = DriverManager.getConnection("jdbc:mysql://localhost/school_info", "root", "");
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(tch_join_form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to connect to the database: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_name6 = new javax.swing.JLabel();
        lbl_name7 = new javax.swing.JLabel();
        txtf_drname = new javax.swing.JTextField();
        txtf_contact = new javax.swing.JTextField();
        txtf_experience = new javax.swing.JTextField();
        join_date = new com.toedter.calendar.JDateChooser();
        btn_join = new javax.swing.JToggleButton();
        birth_date = new com.toedter.calendar.JDateChooser();
        btn_remove = new javax.swing.JToggleButton();
        btn_update = new javax.swing.JToggleButton();
        lbl_name = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        lbl_name2 = new javax.swing.JLabel();
        lbl_name3 = new javax.swing.JLabel();
        txtf_cnic = new javax.swing.JTextField();
        lbl_name4 = new javax.swing.JLabel();
        lbl_name5 = new javax.swing.JLabel();
        txta_address = new java.awt.TextArea();
        txtf_salary = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_search = new javax.swing.JToggleButton();
        txtf_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_home = new javax.swing.JToggleButton();
        btn_main = new javax.swing.JToggleButton();
        lbl_name8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DRIVER REGISTRATION FORM");
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name6.setText("Contact :");
        jPanel2.add(lbl_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 196, 97, 30));

        lbl_name7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name7.setText("Date of Birth");
        jPanel2.add(lbl_name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 244, 97, 31));

        txtf_drname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_drnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtf_drname, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 3, 257, 32));
        jPanel2.add(txtf_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 196, 253, 30));
        jPanel2.add(txtf_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 104, 257, 31));
        jPanel2.add(join_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 287, 257, 30));

        btn_join.setBackground(new java.awt.Color(0, 102, 51));
        btn_join.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_join.setText("JOIN");
        btn_join.setToolTipText("CLICK TO JOIN");
        btn_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinActionPerformed(evt);
            }
        });
        jPanel2.add(btn_join, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, -1));
        jPanel2.add(birth_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 244, 257, 31));

        btn_remove.setBackground(new java.awt.Color(255, 102, 0));
        btn_remove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_remove.setText("REMOVE");
        btn_remove.setToolTipText("CLICK TO REMOVE");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, -1));

        btn_update.setBackground(new java.awt.Color(0, 102, 102));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.setToolTipText("CLICK TO UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 110, -1));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name.setText("Experience");
        jPanel2.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 107, 97, 28));

        lbl_name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name1.setText("Name ");
        jPanel2.add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 18, 93, 26));

        lbl_name2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name2.setText("CNIC NO");
        jPanel2.add(lbl_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 62, 86, 32));

        lbl_name3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name3.setText("Joining Date ");
        jPanel2.add(lbl_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 287, 98, 30));
        jPanel2.add(txtf_cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 53, 257, 33));

        lbl_name4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name4.setText("Salary");
        jPanel2.add(lbl_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 153, 86, 30));

        lbl_name5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name5.setText("Address");
        jPanel2.add(lbl_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 338, 98, 34));
        jPanel2.add(txta_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 338, 257, 58));
        jPanel2.add(txtf_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 154, 253, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.setToolTipText("CLICK TO SEARCH");
        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_search.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 33));

        txtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_idActionPerformed(evt);
            }
        });
        jPanel1.add(txtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 191, 32));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("DRIVER REGISTERATION FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_home.setText("VIEW");
        btn_home.setToolTipText("CLICK TO GO VIEW DRIVER DATA");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 104, -1));

        btn_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_main.setText("BACK");
        btn_main.setToolTipText("CLICK TO GO MAIN MENU");
        btn_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainActionPerformed(evt);
            }
        });
        jPanel1.add(btn_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 104, -1));

        lbl_name8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BUS DRIVER.png"))); // NOI18N
        jPanel1.add(lbl_name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK GROUND IMAGES/DRIVER.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 118, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MAIN_MENU().setVisible(true);
    }//GEN-LAST:event_btn_mainActionPerformed

    private void txtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_idActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try {
            int tchId = Integer.parseInt(txtf_id.getText());
            String sql = "SELECT * FROM driver_info WHERE ID = ?";
            pst = con.prepareStatement(sql);
            pst.setInt(1, tchId);

            rs = pst.executeQuery();
            if (rs.next()) {
                txtf_drname.setText(rs.getString("Driver Name"));
                txtf_contact.setText(rs.getString("Mobile No"));
                txtf_salary.setText(rs.getString("Salary"));
                txta_address.setText(rs.getString("Address"));
            } else {
                JOptionPane.showMessageDialog(this, "Sorry! Record Not Found, Try Again");
            }
        } catch (SQLException ex) {
            Logger.getLogger(tch_join_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txtf_drnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_drnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_drnameActionPerformed

    private void btn_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinActionPerformed
        try {
            pst = con.prepareStatement("INSERT INTO driver_info (`Driver Name`, `Mobile No`, `CNIC No`, `Date of Birth`, `Experience`, `Joining Date`, `Salary`, `Address`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");

            pst.setString(1, txtf_drname.getText());
            pst.setString(2, txtf_contact.getText());
            pst.setString(3, (String) txtf_cnic.getText()); 
            java.sql.Date sqlBirthDate = new java.sql.Date(birth_date.getDate().getTime());
            pst.setDate(4, sqlBirthDate);
            pst.setString(5, txtf_experience.getText());
            java.sql.Date sqlJoinDate = new java.sql.Date(join_date.getDate().getTime());
            pst.setDate(6, sqlJoinDate);
            pst.setString(7, txtf_salary.getText());
            pst.setString(8, txta_address.getText());
            pst.executeUpdate(); // Use executeUpdate() for INSERT queries

            JOptionPane.showMessageDialog(this, "Joined Successfully");

            txtf_drname.setText("");
            txtf_contact.setText("");
            txtf_cnic.setText("");
            birth_date.setDateFormatString("");
             txtf_experience.setText("");
            join_date.setDateFormatString("");
             txtf_salary.setText("");
            txta_address.setText("");
            txtf_drname.requestFocus();

        } catch (SQLException ex) {
            Logger.getLogger(tch_join_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_joinActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        try {
            int ID = Integer.parseInt(txtf_id.getText());
            String sql = "DELETE FROM driver_info WHERE ID = ?";
            pst = con.prepareStatement(sql);
            pst.setInt(1, ID);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record deleted successfully");
            txtf_drname.setText("");
            txtf_contact.setText("");
              txtf_salary.setText("");
            txta_address.setText("");
            txtf_drname.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(tch_join_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            String sql = "UPDATE driver_info SET `Driver Name` = ?, `Mobile No` = ?, Salary = ?, Address = ? WHERE ID = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txtf_drname.getText());
            pst.setString(2, txtf_contact.getText());
            pst.setString(3, txtf_salary.getText());
            pst.setString(4, txta_address.getText());
            pst.setString(5, txtf_id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated");

            txtf_drname.setText("");
            txtf_contact.setText("");
            txta_address.setText("");
            txtf_drname.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new driver_view_info().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(driver_reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(driver_reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(driver_reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(driver_reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new driver_reg_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birth_date;
    private javax.swing.JToggleButton btn_home;
    private javax.swing.JToggleButton btn_join;
    private javax.swing.JToggleButton btn_main;
    private javax.swing.JToggleButton btn_remove;
    private javax.swing.JToggleButton btn_search;
    private javax.swing.JToggleButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser join_date;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_name6;
    private javax.swing.JLabel lbl_name7;
    private javax.swing.JLabel lbl_name8;
    private java.awt.TextArea txta_address;
    private javax.swing.JTextField txtf_cnic;
    private javax.swing.JTextField txtf_contact;
    private javax.swing.JTextField txtf_drname;
    private javax.swing.JTextField txtf_experience;
    private javax.swing.JTextField txtf_id;
    private javax.swing.JTextField txtf_salary;
    // End of variables declaration//GEN-END:variables
}
