/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MAIN_PROJECT;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;


/**
 *
 * @author user
 */
public class tch_salary_receipt extends javax.swing.JFrame {
      Connection con = null;
      PreparedStatement pst = null;
      ResultSet rs = null; 
    /**
     * Creates new form tch_salary_receipt
     */
    public tch_salary_receipt() {
        initComponents();
                try {
        // Establish the database connection in the constructor
        con = DriverManager.getConnection("jdbc:mysql://localhost/school_info", "root", "");
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Std_reg_form.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Failed to connect to the database: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_receipt = new javax.swing.JToggleButton();
        txtf_amount = new javax.swing.JTextField();
        btn_print = new javax.swing.JToggleButton();
        txtf_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtf_tchmobile = new javax.swing.JTextField();
        txtf_tchname = new javax.swing.JTextField();
        btn_reset = new javax.swing.JToggleButton();
        txta = new java.awt.TextArea();
        month = new com.toedter.calendar.JMonthChooser();
        btn_record = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        btn_idsearch = new javax.swing.JToggleButton();
        txtf_idsrch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEACHER SALARY FORM");
        setResizable(false);

        btn_receipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_receipt.setText("RECEIPT");
        btn_receipt.setToolTipText("CLICK TO MAKE RECEIPT");
        btn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiptActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print.setText("PRINT ");
        btn_print.setToolTipText("CLICK TO PRINT RECEIPT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Teacher Name");

        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.setToolTipText("CLICK TO RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        txta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_record.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_record.setText("SAVE RECORD");
        btn_record.setToolTipText("CLICK TO SAVE RECORD");
        btn_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Month");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mobile No.");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Salary Amount");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(1220, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(1220, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEACHER SALARY RECEIPT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 520, -1));

        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setText("BACK");
        btn_menu.setToolTipText("CLICK TO GO MAIN MENU");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Teacher-icon.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_idsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_idsearch.setText("SEARCH");
        btn_idsearch.setToolTipText("CLICK TO SEARCH");
        btn_idsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idsearchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_idsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));

        txtf_idsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_idsrchActionPerformed(evt);
            }
        });
        jPanel2.add(txtf_idsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtf_amount)
                                        .addComponent(txtf_tchname, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtf_tchmobile, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtf_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_record, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_print)
                                .addGap(18, 18, 18)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_tchname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_tchmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtf_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_reset)
                            .addComponent(btn_receipt)
                            .addComponent(btn_print)
                            .addComponent(btn_record)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(684, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_idsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idsearchActionPerformed
        // TODO add your handling code here:
                try {
    if (!txtf_idsrch.getText().isEmpty()) {
        int stdId = Integer.parseInt(txtf_idsrch.getText());
        String sql = "SELECT * FROM teacher_info WHERE ID = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, stdId);

        rs = pst.executeQuery();
        if(rs.next()){
            txtf_tchname.setText(rs.getString("Name"));
            txtf_tchmobile.setText(rs.getString("Contact")); 
            txtf_amount.setText(rs.getString("Salary"));
            } else {
            JOptionPane.showMessageDialog(this, "Sorry! Record Not Found, Try Again");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please enter a valid ID");
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Please enter a valid ID");
} catch (SQLException ex) {
    Logger.getLogger(Std_reg_form.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_btn_idsearchActionPerformed

    private void btn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiptActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        // TODO add your handling code here:
    txta.setText("********************************************************************************************************\n");
    txta.append("****************************************SALARY Receipt**********************************************\n");
    txta.append("****************************************------------ ----------**********************************************\n");
    txta.append("********************************************************************************************************\n\n\n");        
    txta.append("\t\t\tStudent Name : \t\t" + txtf_tchname.getText() + "\n\n");
    txta.append("\t\t\tMobile No  : \t\t" + txtf_tchmobile.getText() + "\n\n");
    txta.append("\t\t\tDate \t: \t\t" + sdf.format(txtf_date.getDate()) + "\n\n");
    txta.append("\t\t\tSalary \t: \t\t" + txtf_amount.getText() + "\n\n"); // Use getSelectedItem instead of getItemAt
     txta.append("\t\t\tMonth \t: \t\t" + getMonthName(month.getMonth()) + "\n\n");
    
    
    
    
    
    
   
    
    txta.append("\n\n\n\n\n\n\n\n\n\n------------ -------------\t\t\t\t\t\t\t----------- -------------\n");
    txta.append("Principle Signature\t\t\t\t\t\t\tTeacher Signature");
    }//GEN-LAST:event_btn_receiptActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
        // Create a PrinterJob
        PrinterJob job = PrinterJob.getPrinterJob();

        // Create a Printable object for the TextArea content
        Printable printable = new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check if the page index is within the range
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                // Get the Graphics2D object
                Graphics2D g2d = (Graphics2D) graphics;

                // Set the translation to fit the TextArea content within the page
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                // Print the TextArea content
                txta.printAll(g2d);

                // Return that the page is printable
                return Printable.PAGE_EXISTS;
            }
        };

        // Set the Printable object for the PrinterJob
        job.setPrintable(printable);

        // Show print dialog to allow user to choose printer and set print options
        if (job.printDialog()) {
            // If user selects OK in the print dialog, print the document
            job.print();
        }
    } catch (PrinterException ex) {
        JOptionPane.showMessageDialog(this, "Printing failed: " + ex.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txta.setText("");
       txtf_tchname.setText("");
       txtf_tchmobile.setText("");
       txtf_date.setDateFormatString("");
       txtf_amount.setText("");
       month.setName("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recordActionPerformed
        // TODO add your handling code here:
        try {
        pst = con.prepareStatement("INSERT INTO teacher_salary (`Teacher Name`,`Mobile No`, `Date`, `Salary`, `Month`) VALUES (?, ?, ?, ?, ?)");
        
        pst.setString(1, txtf_tchname.getText());
        pst.setString(2, txtf_tchmobile.getText());
        java.sql.Date sqlBirthDate = new java.sql.Date(txtf_date.getDate().getTime());
        pst.setDate(3, sqlBirthDate);
        pst.setString(4, txtf_amount.getText());
      // Get the index of the selected month
        int monthIndex = month.getMonth();
        // Map the index to the corresponding month name
        String monthName = getMonthName(monthIndex);
        pst.setString(5, monthName);

        pst.executeUpdate(); // Use executeUpdate() for INSERT queries
        
        JOptionPane.showMessageDialog(this, "Record Save Successfully");
        
//        txtf_tchname.setText("");
//        txtf_tchmobile.setText("");
//        txtf_date.setDate(null);
//        txtf_amount.setText("");
//        month.setName("");
//        txtf_tchname.requestFocus();

    } catch (SQLException ex) {
        Logger.getLogger(Std_reg_form.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_recordActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MAIN_MENU().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void txtf_idsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_idsrchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_idsrchActionPerformed
       private String getMonthName(int monthIndex) {
        String[] monthNames = new DateFormatSymbols().getMonths();
        return monthNames[monthIndex]; }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tch_salary_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tch_salary_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tch_salary_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tch_salary_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tch_salary_receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_idsearch;
    private javax.swing.JToggleButton btn_menu;
    private javax.swing.JToggleButton btn_print;
    private javax.swing.JToggleButton btn_receipt;
    private javax.swing.JToggleButton btn_record;
    private javax.swing.JToggleButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JMonthChooser month;
    private java.awt.TextArea txta;
    private javax.swing.JTextField txtf_amount;
    private com.toedter.calendar.JDateChooser txtf_date;
    private javax.swing.JTextField txtf_idsrch;
    private javax.swing.JTextField txtf_tchmobile;
    private javax.swing.JTextField txtf_tchname;
    // End of variables declaration//GEN-END:variables
}
